#ifndef OS_INCLUDE_VGA_VIDEO_COLOR_H
#define OS_INCLUDE_VGA_VIDEO_COLOR_H

typedef enum {
        VIDEO_BLACK = 0,
        VIDEO_BLUE,
        VIDEO_GREEN,
        VIDEO_CYAN,
        VIDEO_RED,
        VIDEO_MAGENTA,
        VIDEO_YELLOW,
        VIDEO_LIGHT_GRAY,
        NAVY,
        VIDEO_LIGHT_BLUE,
        VIDEO_LIGHT_GREEN,
        VIDEO_LIGHT_CYAN,
        VIDEO_LIGHT_RED,
        VIDEO_LIGHT_MAGENTA,
        DESERT_GREEN,
        LIGHT_PURPLE,
        DARK_GREEN,
        DULL_BLUE,
        BRIGHT_LIME,
        TEAL,
        TERRACOTTA_BROWN,
        DULL_PURPLE,
        YELLOW_GREEN,
        WHITE_GREEN,
        BLUE_GREEN,
        MATTE_BLUE,
        MINT_GREEN,
        BABY_BLUE,
        BRICK_RED,
        BRIGHT_PURPLE,
        UNNAMED_GREEN1,
        WHITE_BLUE,
        WINE_RED,
        GRIMACE_PURPLE,
        OLIVE_GREEN,
        DULL_GREY_BLUE,
        HOT_BRIGHT_RED,
        HOT_PINK,
        ORANGE,
        PEACH,
        DARK_PURPLE,
        RETRO_BLUE,
        UNNAMED_GREEN2,
        SKY_BLUE,
        RED_PINK,
        HOT_MAGENTA,
        TAN,
        LIGHT_PINK,
        JUNGLE_GREEN,
        GRAY_BLUE,
        NEON_GREEN,
        MINT_GREEN2,
        DARK_ORANGE,
        BRIGHT_PINK,
        BRIGHT_YELLOW,
        MATTE_YELLOW,
        MATTE_GRAY,
        UNNAMED_BLUE1,
        UNNAMED_GREEN3,
        UNNAMED_BLUE2,
        UNNAMED_RED1,
        UNNAMED_PINK1,
        UNNAMED_YELLOW1,
        VIDEO_WHITE
} VideoColor;

#endif